name: yoyo_school_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.35

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.1
  flutter_otp_text_field: ^1.1.0+2
  pin_code_fields: ^8.0.1
  otp_autofill: ^4.1.0
  palette_generator: ^0.3.3+7
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  fluttertoast: ^9.0.0
  just_audio: ^0.10.5
  audio_waveforms: ^1.3.0
  crypto: ^3.0.6
  http: ^1.5.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^3.2.0
  rive: ^0.13.20
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Sansita
      fonts:
        - asset: assets/fonts/SansitaOne.ttf
  generate: true
